pnpMode: strict

packageExtensions:
  "@golevelup/nestjs-common@*":
    dependencies:
      "lodash": "*"
      "@nestjs/common": "*"
  "@golevelup/nestjs-discovery@*":
    dependencies:
      "@nestjs/common": "*"
      "@nestjs/core": "*"
  "@golevelup/nestjs-modules@*":
    dependencies:
      rxjs: "*"
  "@golevelup/nestjs-stripe@*":
    dependencies:
      "lodash": "*"
      "@nestjs/common": "*"
      "@nestjs/core": "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
