pnpMode: strict

packageExtensions:
  "@golevelup/nestjs-common@*":
    dependencies:
      "lodash": "*"
  "@golevelup/nestjs-stripe@*":
    dependencies:
      "lodash": "*"
      "rxjs": "*"
      "@nestjs/common": "*"
      "reflect-metadata": "*"
#      "@nestjs/core": "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
